#!/bin/sh export 
GPU_MAX_HEAP_SIZE=100export 
GPU_MAX_USE_SYNC_OBJECTS=1export 
GPU_SINGLE_ALLOC_PERCENT=100export 
GPU_MAX_ALLOC_PERCENT=100export 
GPU_MAX_SINGLE_ALLOC_PERCENT=100export 
GPU_ENABLE_LARGE_ALLOCATION=100export 
GPU_MAX_WORKGROUP_SIZE=1024 
./SRBMiner-MULTI --config-file ./Config/config-yespowerlitb.txt --pools-file ./p-litb.txt
